server:
  http:
    port: 8080
logging:
  level:
    org.springframework.web: INFO
spring:
  application:
    name: webui
  groovy:
    template:
      enabled: true
songdata:
  # if not running in docker compose use localhost
  # e.g. ./gradlew bootRun --args='--songdata.host=localhost'
  host: songdata
  port: 8086
  songs:
    path: /v1/songs
  artists:
    path: /v1/artists
