INSERT INTO ARTIST (ID, NAME) VALUES (1, 'Muse');
INSERT INTO ARTIST (ID, NAME) VALUES (2, 'They Might Be Giants');
INSERT INTO ARTIST (ID, NAME) VALUES (3, 'David Bowie');
INSERT INTO ARTIST (ID, NAME) VALUES (4, 'Elton John');

INSERT INTO SONG (ID, TITLE, ARTISTID) VALUES (1, 'Supermassive Black Hole', 1);
INSERT INTO SONG (ID, TITLE, ARTISTID) VALUES (2, 'Why Does the Sun Really Shine?', 2);
INSERT INTO SONG (ID, TITLE, ARTISTID) VALUES (3, 'Space Oddity', 3);
INSERT INTO SONG (ID, TITLE, ARTISTID) VALUES (4, 'Rocket Man', 4);
